version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "nginx-proxy"
          ContainerPort: 80
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["<SUBNET_ID_1>", "<SUBNET_ID_2>"]
            SecurityGroups: ["<SECURITY_GROUP_ID>"]
            AssignPublicIp: "DISABLED" 